Framer motion
RRamirez1414/crud-react-ts-app pull request #11
Opened 2021-05-26 22:43 UTC by RRamirez1414

2021-05-26 23:02 UTC, m1yon requested changes

2021-05-26 23:02 UTC, m1yon commented on src/components/Card.tsx
> +          transition={{ duration: 0.2, ease: 'easeOut' }}
```suggestion
          transition={{ duration: 0.2, ease: 'easeIn' }}
```

You want the user to be able to see and click the underlining as soon as possible. eastOut is technically correct (fast at beginning and slow at end), but it's flipped here for some reason

2021-05-26 23:02 UTC, m1yon commented on src/components/Card.tsx
> +                {pathname === '/search' ? (
this "In Collection" text and delete button animations are being played twice for some reason. Happens about 50% of the time for me.

2021-05-26 23:02 UTC, m1yon commented on src/components/Card.tsx
> +                    transition={{ transition: 0.5 }}
The add button also flashes it's finished state before playing the animation sometimes

2021-05-26 23:02 UTC, m1yon commented on src/components/Loader.tsx
> +const Loader = () => {
nice!

2021-05-27 16:15 UTC, RRamirez1414 commented on src/components/Card.tsx
> +          transition={{ duration: 0.2, ease: 'easeOut' }}
found the problem, I did not take out the transition ease in the twin macro styles, easeOut works as expected now

2021-05-27 21:54 UTC, m1yon requested changes
looks good, the only big thing I notice is when navigating between the search pages, the cards will briefly show the info overlay which makes it feel a bit jankey. After that though I think it's perfect.

2021-05-27 21:54 UTC, m1yon commented on src/components/CardButton.tsx
> +const CardButton = ({ cardData }: CardProps) => {
I wouldn't reuse component prop types like this, you already have the PokemonCard type to help you not repeat yourself

2021-05-27 21:54 UTC, m1yon commented on src/components/CardButton.tsx
> +const CardButton = ({ cardData }: CardProps) => {
react components prop types should always be 1-to-1

2021-05-27 21:54 UTC, m1yon commented on src/utils/isCollected.ts
> +  return cards.find((card) => card.id === id) ? true : false
```suggestion
  return cards.some((card) => card.id === id)
```

some() is like find() but it'll return a boolean instead of the object/undefined

2021-06-01 15:19 UTC, m1yon approved these changes

2021-06-01 15:26 UTC, merged