introduced cypress for testing
RRamirez1414/crud-react-ts-app pull request #8
Opened 2021-05-20 17:32 UTC by RRamirez1414

2021-05-20 18:06 UTC, m1yon requested changes

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/examples/actions.spec.js
> +/// <reference types="cypress" />
you can remove this entire examples folder

2021-05-20 18:06 UTC, m1yon commented on package.json
>    "devDependencies": {
you definitely need to add a command in the "scripts" section here to start and your dev server AND open Cypress in one go: https://docs.cypress.io/guides/getting-started/installing-cypress#Adding-npm-scripts

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/add-searched.ts
> +export const addSearched = () => {
this test doesn't even run for me since your wrapping it in a function haha

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +describe("Let's delete from collection", () => {
no need for a describe block, I'd only use these to group common tests

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +  it('Adds cards from search page', () => {
```suggestion
  it('can add cards from search page to the collection', () => {
```

this should read like a sentence (starting with "it")

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +    cy.contains('Search').click()
```suggestion
    cy.findByRole('link', { name: 'Search' }).click()
```

Make sure your always opting to use cypress-testing-library when querying and not the default Cypress stuff.

You also want to try to query by aria roles when you can (that way we're testing accessibility at the same time!)

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +    cy.wait(2000)
using a wait() in your tests should always be a huge flag, ideally you never have any wait()'s

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +    const cardButtons = cy.get('figure > figcaption > div').find('>button')
Cypress doesn't work like this, you can store variables in Cypress. https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Return-Values

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +    const cardButtons = cy.get('figure > figcaption > div').find('>button')
you're query is also wayyy to implementation heavy. What happens if we change the figcaption to a div? What happens if we the figure wrapper? 

E2E and integration tests should be implementation agnostic, you should be able to write a test, refactor all the components completely, and your tests should still pass in the end without having to change your tests (assuming you didn't change button text or anything)

You should definitely be using findByRole or findAllByRole here

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +      cy.wrap(cardButton).click({ force: true })
I would force: true here either since the button isn't really visible, I'd hover first then click on it without the force: true

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +    cy.wait(2000)
you never assert whether the cards actually got added to the collection? At the end here, you need to make sure all the cards you added in fact got added (use should())

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +    const cardButtons = cy
you should always reset your tests before starting - cy.visit('/')

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/delete-collection.ts
> +    })
you need assertions here, that's the most important part of the test!

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/tsconfig.json
> +{
the test runner shouldn't be picking up this file

2021-05-20 18:06 UTC, m1yon commented on src/components/CardGrid.tsx
> +  return <Grid id="card-grid">{children}</Grid>
you shouldn't need this

2021-05-20 18:06 UTC, m1yon commented on cypress/integration/add-searched.ts
> +    it('Visits the Pokemon Collection Search Page', () => {
unnecessary tests. For E2E tests, I would just check all the "Happy Path" interactions the user can do. In your case, the only tests you need is creating and deleting cards. You can also tests some stuff along the way too (search box, etc)

2021-05-20 18:12 UTC, RRamirez1414 commented on cypress/integration/add-searched.ts
> +export const addSearched = () => {
my bad, earlier I tried to export this function and run it in another test, but ran into issues, I forgot to revert it lol

2021-05-21 20:51 UTC, m1yon requested changes

2021-05-21 20:51 UTC, m1yon commented on cypress/integration/add-delete-collection.ts
> +  const cardFigures = cy.findAllByRole('figure').should('exist')
you can't use variables in Cypress like this: https://docs.cypress.io/guides/core-concepts/variables-and-aliases

<img width="694" alt="Screen Shot 2021-05-21 at 2 40 43 PM" src="https://user-images.githubusercontent.com/37197876/119195867-8b250880-ba42-11eb-94e4-a65a69fb4ede.png">

2021-05-21 20:51 UTC, m1yon commented on cypress/integration/add-delete-collection.ts
> +  cy.findAllByRole('link', { name: 'Search' }).click()
your finding all links with the name role, but which one are you clicking? findAllBy* is going to return an array, you need to specify which one you want to click.

2021-05-21 20:51 UTC, m1yon commented on cypress/integration/add-delete-collection.ts
> +  cardFigures.each((cardFigure) => {
you definitely don't need to do all of these lol, I'd do like 2 maybe 3

2021-05-21 20:51 UTC, m1yon commented on cypress/integration/add-delete-collection.ts
> +      .should('be.visible')
don't need assert this, you won't be able to click if it's not visible

2021-05-21 20:51 UTC, m1yon commented on cypress/integration/add-delete-collection.ts
> +      .realClick()
this definitely seems like I hack haha, I'd either use cypress-real-events for your events or the default cypress events

2021-05-21 20:51 UTC, m1yon commented on cypress/integration/add-delete-collection.ts
> +      .findByRole('button')
this is too generic, I'd query by the name too

2021-05-21 20:51 UTC, m1yon commented on cypress/integration/add-delete-collection.ts
> +export {}
you shouldn't need this

2021-05-24 15:38 UTC, m1yon approved these changes

2021-05-24 18:26 UTC, merged